name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: wealth-link-platform
          POSTGRES_USER: weatlh
          POSTGRES_PASSWORD: dummy-password-for-tests
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for SonarCloud

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test with Maven
        # Override the datasource properties to point to the local GitHub Postgres service
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/wealth-link-platform
          SPRING_DATASOURCE_USERNAME: weatlh
          DB_PASSWORD: "dummy-password-for-tests"
        run: mvn clean verify

      - name: Analyze with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=rushikeshmind2000-star_Wealth-Link-platform -Dsonar.organization=rushikeshmind2000-star -Dsonar.host.url=https://sonarcloud.io

  docker-build:
    needs: build-test-analyze
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t wealth-link-platform:latest .
